In [1]:
import pandas as pd
import numpy as np
df1=pd.read_csv('KOLKATA_HOUSE_PRICE_2.csv')
df1


Flat_Price EMI_Starts  BHK         Location  Total_sq.ft Price_per_sq.ft  \
0        8.5 Cr  4.22 Lacs  6.0       Ballygunge         4200           20.24   
1        45.0 L    23.83 K  3.0      Barrackpore         1400            3.21   
2       1.35 Cr    67.02 K  3.0       Santoshpur         2500             5.4   
3        60.0 L    31.77 K  5.0          Sarsuna         1100            5.45   
4        52.0 L    27.54 K  4.0      Madhyamgram          900            5.78   
...         ...        ...  ...              ...          ...             ...   
3902     13.0 L     6.88 K  2.0    Picnic Garden         1500       866/sq.ft   
3903     1.5 Cr    74.47 K  8.0  Rajpur Sonarpur         2560            5.86   
3904     50.0 L    26.48 K  5.0           Amtala         1900            2.63   
3905     1.1 Cr    54.61 K  5.0       Tollygunge         2600            4.23   
3906     30.0 L    15.89 K  2.0          Naihati          950            3.16   

        EMI  Flat_Price_K  
0       422         85000  
1     23.83          4500  
2     67.02         13500  
3     31.77          6000  
4     27.54          5200  
...     ...           ...  
3902   6.88          1300  
3903  74.47         15000  
3904  26.48          5000  
3905  54.61         11000  
3906  15.89          3000  

[3907 rows x 8 columns]

In [2]:
df1.isna().sum()


Flat_Price         0
EMI_Starts         0
BHK                0
Location           0
Total_sq.ft        0
Price_per_sq.ft    0
EMI                0
Flat_Price_K       0
dtype: int64

In [3]:
df1.isnull().sum()

Flat_Price         0
EMI_Starts         0
BHK                0
Location           0
Total_sq.ft        0
Price_per_sq.ft    0
EMI                0
Flat_Price_K       0
dtype: int64

In [4]:
df1["BHK"].unique()


array([ 6. ,  3. ,  5. ,  4. ,  2. ,  9. , 10. ,  7. ,  8. ,  1. , 10.5,
        3.5,  2.5,  8.5])

In [5]:
df2=df1.drop(['Flat_Price','EMI_Starts'],axis='columns')

In [6]:
df2

BHK         Location  Total_sq.ft Price_per_sq.ft    EMI  Flat_Price_K
0     6.0       Ballygunge         4200           20.24    422         85000
1     3.0      Barrackpore         1400            3.21  23.83          4500
2     3.0       Santoshpur         2500             5.4  67.02         13500
3     5.0          Sarsuna         1100            5.45  31.77          6000
4     4.0      Madhyamgram          900            5.78  27.54          5200
...   ...              ...          ...             ...    ...           ...
3902  2.0    Picnic Garden         1500       866/sq.ft   6.88          1300
3903  8.0  Rajpur Sonarpur         2560            5.86  74.47         15000
3904  5.0           Amtala         1900            2.63  26.48          5000
3905  5.0       Tollygunge         2600            4.23  54.61         11000
3906  2.0          Naihati          950            3.16  15.89          3000

[3907 rows x 6 columns]

In [7]:
df2['Price_per_sq.ft']=df2['Price_per_sq.ft'].apply(lambda x: x.split('/')[0])


In [8]:
dummies=pd.get_dummies(df2.Location)

In [9]:
df3=pd.concat([df2,dummies],axis='columns')
df3['EMI']=df3['EMI'].apply(lambda x: x if x!='#VALUE!' else None)
df3=df3.dropna()
df3['Price_per_sq.ft']=df3['Price_per_sq.ft'].astype(float)
df3['EMI']=df3['EMI'].astype(float)
df3['BHK']=df3['BHK'].astype(float)
df3['Total_sq.ft']=df3['Total_sq.ft'].astype(float)
df3['Flat_Price_K']=df3['Flat_Price_K'].astype(float)


In [10]:
df3['Total_sq.ft'].unique()

array([ 4200.,  1400.,  2500.,  1100.,   900.,  1200.,  2310.,  1170.,
        1862.,  1800.,  1650.,  5000., 15000.,  1500.,  1440.,  1450.,
        4000.,  3000.,  2584.,   720.,  2000.,  2200.,  6000.,  9720.,
        6068.,  2886.,  1876.,  2800.,  1470.,  3600.,  1750.,  1308.,
       12000.,  1395.,  1567.,  1906.,   620.,  4500.,   834.,  5200.,
        2100.,  1300.,  4320.,  1080.,  1560.,  1480.,  2750.,  3500.,
        2400.,  1000.,  1180.,  2420.,  2366.,  1070., 11500.,  1552.,
        4400.,  3240.,   800.,  2300.,   850., 14000.,  1270.,   910.,
        1250.,  1600.,   700.,   750.,   880.,  3300.,  2525.,  3400.,
        1280.,  1428.,  3700.,  4753.,   980., 10000.,  1345.,  3200.,
         630.,   875.,  1700.,  4800.,  7500.,  1982.,  1088.,  3658.,
        1910.,  1284.,  1758.,  1095.,  2180.,  1453.,  1465.,  1485.,
        1680.,  1530.,  1810.,  1110.,  3270.,  1123.,  1260.,  1935.,
         948.,   988.,  1858.,   866.,  1150.,  1550.,  2880.,  2700.,
      

In [11]:
y=df3.Flat_Price_K
x=df3.drop(['Flat_Price_K','Location','Price_per_sq.ft'],axis='columns')


In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.3)


In [13]:
from sklearn.linear_model import LinearRegression
model1= LinearRegression()
model1.fit(X_train,y_train)
model1.score(X_test,y_test)

0.9999795017862658

In [14]:
model1.predict(x[1:4])

array([ 4591.72835429, 13420.93173388,  6173.55139231])

In [15]:
def predict_price(location,emi,bhk,total_sq_ft): 
    a = np.zeros(len(x.columns))
    a[0] = bhk
    a[1] = total_sq_ft
    a[2] = emi
    
    for i in range(3,len(x.columns)):
        if(location==x.columns[i]):
            a[i] = 1
            return model1.predict([a])*1000
            break

    
    

    

In [21]:
predict_price('Madhyamgram',27.54,4,900)

C:\Users\Sourav Bhowal\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([5264727.99986475])

In [17]:
import pickle
with open('Kolkata_house_price_pridicator_1.pickle','wb') as f:
    pickle.dump(model1,f)

In [18]:
import json
columns = {
    'data_columns' : [col.lower() for col in x.columns]
}
with open("columns.json","w") as f:
    f.write(json.dumps(columns))

In [19]:
x

BHK  Total_sq.ft     EMI  Abdalpur  Adarsha Nagar  Agarpara  Airport  \
0     6.0       4200.0  422.00     False          False     False    False   
1     3.0       1400.0   23.83     False          False     False    False   
2     3.0       2500.0   67.02     False          False     False    False   
3     5.0       1100.0   31.77     False          False     False    False   
4     4.0        900.0   27.54     False          False     False    False   
...   ...          ...     ...       ...            ...       ...      ...   
3902  2.0       1500.0    6.88     False          False     False    False   
3903  8.0       2560.0   74.47     False          False     False    False   
3904  5.0       1900.0   26.48     False          False     False    False   
3905  5.0       2600.0   54.61     False          False     False    False   
3906  2.0        950.0   15.89     False          False     False    False   

      Alipore  Amtala  Ariadaha  ...  Thakuranir Chak  Thakurpukur  Tiljala  \
0       False   False     False  ...            False        False    False   
1       False   False     False  ...            False        False    False   
2       False   False     False  ...            False        False    False   
3       False   False     False  ...            False        False    False   
4       False   False     False  ...            False        False    False   
...       ...     ...       ...  ...              ...          ...      ...   
3902    False   False     False  ...            False        False    False   
3903    False   False     False  ...            False        False    False   
3904    False    True     False  ...            False        False    False   
3905    False   False     False  ...            False        False    False   
3906    False   False     False  ...            False        False    False   

      Tollygunge  Topsia  Ultadanga  Uttarbhag  VIP Nagar  Vedic Village  \
0          False   False      False      False      False          False   
1          False   False      False      False      False          False   
2          False   False      False      False      False          False   
3          False   False      False      False      False          False   
4          False   False      False      False      False          False   
...          ...     ...        ...        ...        ...            ...   
3902       False   False      False      False      False          False   
3903       False   False      False      False      False          False   
3904       False   False      False      False      False          False   
3905        True   False      False      False      False          False   
3906       False   False      False      False      False          False   

      Ward No 113  
0           False  
1           False  
2           False  
3           False  
4           False  
...           ...  
3902        False  
3903        False  
3904        False  
3905        False  
3906        False  

[3906 rows x 204 columns]

In [20]:
x.columns[5]

'Agarpara'